version: '3.9'

services:
  wbd-soap-service:
    container_name: wbd-soap-service
    build:
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      wbd-soap-db:
        condition: service_healthy
    
  wbd-soap-db:
    container_name: wbd-soap-db
    image: mysql:5.7.43
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$$MYSQL_DATABASE
      - MYSQL_USER=$$MYSQL_USER
      - MYSQL_PASSWORD=$$MYSQL_PASSWORD
    env_file:
      - .env
    volumes:
      - wbd-soap-dbdata:/var/lib/mysql/
      - /mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: mysql -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
      interval: 5s
      timeout: 5s
      retries: 10